export const lng_main = {
			en: {
				impCompl: 		"Import complete.",
				added: 			"Added: ",
				updated: 		"Updated: ",
				skipped: 		"Skipped: ",
				bluebtn: 		"Zoom window",
				ttCancel:      	"Cancel",
				ttStart:       	"Start",
				tPoint:			".",

				// red button
				close1: 		"Close AstroSpy",
				redbtn: 		"Menue with further features",
				bAllUnits:		"All units",
				tAllUnits:		"Opens a window with data on all maps, ships and bases\nfrom maps already visited.",
				bShipsPerMap:	"My ships per map",
				tShipsPerMap:	"Opens a window with overview of ships\nper map.",
				bScanner:		"Map Scanner",
				tScanner:		"Opens a pop-up window to automatically scan/visit\nmaps one after the other.",
				bMessages:		"Show messages",
				tMessages:		"Last messages will be shown, e.g. enemies on a map.",
				bChangePlAlly: 	"Change players's ally",
				tChangePlAlly: 	"Opens a pop-up window to change player's\nally after he flipped to a different one.",
				bChangePlName: 	"Change player's name",
				tChangePlName: 	"Opens a pop-up window to change player's\nname after he renamed.",
				bResetMyAlly:	"Reset my ally on a map",
				tResetMyAlly:	"Use this button to clear your ally base data on a map.",
				tpResetMyAlly1: "This function will reset the base data of your ally only on a map.\nUseful if your ally lost bases.\nMap number must be between 11 and ",
				tpResetMyAlly2: "\nIMPORTANT: switch first to a different map or it won't work.",
				tpResetMyAlly3: "You are trying to reset the data from the currently active map.\nSwitch to a different map and try again.",
				bResetAnyAlly: 	"Reset any ally on a map",
				tResetAnyAlly: 	"Use this button to clear your any base data on a map.",
				
				// green button
				bExpBasesOneMap:"Export bases of one map",
				tExpBasesOneMap:"Export bases of a particular map to a CSV file.",
				pExpBasOneMap1:	"This function will export a map to a CSV file.\nFile will be stored in your standard DOWNLOADS folder.\nMap number must be greater than 10 and less than",
				bExpBasesAllMaps:"Export bases of all maps",
				tExpBasesAllMaps:"Export bases of all maps to a CSV file.",
				pExpBasesAllMaps:"This function will export all maps to a CSV file.\nFile will be stored in your standard DOWNLOADS folder. Proceed?",
				bExpBasesOnePl:	"Export bases of one player",
				tExpBasesOnePl:	"Export bases of one player to a CSV file.",
				bExpBasesOneAl: "Export all bases of one ally",
				tExpBasesOneAl:	"Export all bases of a particular ally to a CSV file.",
				iExpInputErr:	"Your input is either not numeric or not between 11 and ",
				bImpBases: 		"Import bases",
				tImpBases:		"Import bases from a CSV file.",
				bImpShips:		"Import ships",
				tImpShips:		"Import ships from a CSV file.",
				bImpBookmarks:	"Import bookmarks",
				tImpBookmarks:	"Import bookmarks from a CSV file.",
				bExpComOneMap:	"Export comment of one map",
				tExpComOneMap: 	"Export comment of a particular map to a CSV file.",
				bExpComAllMaps:	"Export comments of all maps",
				tExpComAllMaps:	"Export comments of all maps to a CSV file.",
				bImpComments:	"Import comments",
				tImpComments:	"Import map comments from a CSV file.",	
		
				// popups import
				pBaseTitle:     "Import bases from CSV file to your database.",
				pShipTitle:		"Import ships from CSV file to your database.",
				pBookmarkTitle:	"Import bookmarks from CSV file to your database.",
				pCommentTitle:	"Import map comments from CSV file to your database.",
				pDescription:   "Depending on file size import might take up to a few minutes.",
				pBtnChooseFile: "Choose file...",
				pNoFileChosen:  "No file chosen",
				pBtnImport:     "Import Data",
				pErrNoFile:     "Please select a CSV file.",
				
				// popup map scanner
				sc_title:       "Map-Scanner",
                sc_description: "The specified maps are visited in sequence and thus saved.",
                sc_speed:       "Map scanner handles approx.\u00a015\u201320 maps per minute.",
                sc_attention:   "ATTENTION:\u00a0Avoid using it too often!",
                sc_warning:     "Hoppe might well notice such regular quick requests.",
                sc_from:        "From map number:",
                sc_to:          "Until map number:",
                sc_rbBase:      "Only maps with bases or ships from me.\u00a0",
                sc_rbShip1:     "Maps with bases and ships from my ally\u00a0(excl.\u00a0my maps).",
                sc_rbShip:      "Maps with bases and ships from my ally.",
                sc_rbShip2:     "All maps excl.\u00a0maps of my ally.",
                sc_rbAll:       "All maps.",
                sc_btnStart:    "Scan",
                sc_ttStart:     "Starts scanning the specified maps.",
                sc_errMaxMap:   "The to value must be smaller than the maximum number of maps! ({max})",
                sc_errFromTo:   "The from value must be smaller than the \"until\" value!",
                sc_errMinFrom:  "The from value must be 11 or higher!",
			},
			de: {
				impCompl: 		"Import fertig.",
				added: 			"Hinzugefügt: ",
				updated: 		"Aktualisiert: ",
				skipped: 		"Übersprungen: ",
				bluebtn: 		"Zoom Fenster",
				ttCancel:      	"Abbrechen",
				ttStart:       	"Starten",
				tPoint:			".",

				// red button
				close1: 		"AstroSpy schließen",
				redbtn: 		"Menu mit weiteren Funktionen",
				bAllUnits:		"Alle Einheiten",
				tAllUnits:		"Öffnet ein Fenster mit Übersicht aller Karten, \nBasen und Schiffe der besuchten Karten.",
				bShipsPerMap:	"Meine Schiffe pro Karte",
				tShipsPerMap:	"Öffnet ein Fenster mit der Übersicht\nmeiner Schiffe pro Karte.",
				bScanner:		"Kartenscanner",
				tScanner:		"Öffnet ein Popup-Fenster, um die Karten\nnacheinender zu besuchen/scannen.",
				bMessages:		"Nachrichten anzeigen",
				tMessages:		"Letzte Nachrichten werden angezeigt.\nZ.B. Feinde auf einer Karte.",
				bChangePlAlly: 	"Ally eines Spieler's ändern",
				tChangePlAlly: 	"Öffnet ein Popup-Fenster, um die Ally des Spielers zu\nändern, nachdem er zu einer anderen gewechselt ist.",
				bChangePlName: 	"Name eines Spieler's ändern",
				tChangePlName: 	"Öffnet ein Popup Fenster, um den Namen eines\nSpieler's zu ändern wenn er sich umbenannt hat.",
				bResetMyAlly: 	"Reset meine Ally auf einer Karte",
				tResetMyAlly: 	"Verwende diesen Button, um die Map deiner Ally zurückzusetzen.",	
				tpResetMyAlly1: "Diese Funktion setzt die Basisdaten deiner Ally nur auf einer Karte zurück.\nNützlich, wenn deine Ally Basen verloren hat.\nDie Kartennummer muss zwischen 11 und ",
				tpResetMyAlly2: " sein.\nWICHTIG: Wechsle zuerst zu einer anderen Karte, sonst funktioniert es nicht.",
				tpResetMyAlly3: "Du versuchst, die Daten der derzeit aktiven Karte zurückzusetzen.\nWechsle zu einer anderen Karte und versuche es erneut.",
				bResetAnyAlly: 	"Reset irgendeine Ally auf einer Karte",
				tResetAnyAlly: 	"Verwende diesen Button, um irgendeine\nAlly auf der Map zurückzusetzen.",	
				
				// green button
				bExpBasesOneMap:"Export Basen von einer Karte",
				tExpBasesOneMap:"Export Basen von einer bestimmten Karte\nin eine CSV Datei.",
				pExpBasOneMap1:	"Diese Funktion exportiert eine Karte in eine CSV-Datei.\nDie Datei wird im Standardordner „DOWNLOADS“ gespeichert.\nDie Kartennummer muss größer als 10 und kleiner als ",
				pExpBasOneMap2:	" sein.",
				bExpBasesAllMaps:"Export Basen von allen Karten",
				tExpBasesAllMaps:"Export Basen aller Maps in CSV Datei.",
				pExpBasesAllMaps:"Diese Funktion exportiert alle Karten in eine CSV-Datei.\nDie Datei wird in Ihrem Standardordner „DOWNLOADS“ gespeichert. Fortfahren?",
				bExpBasesOnePl:	"Export Basen von einem Spieler",
				tExpBasesOnePl:	"Export Basen von einem Spieler in CSV Datei.",
				bExpBasesOneAl: "Export aller Basen einer Ally",
				tExpBasesOneAl:	"Export aller Basen einer Ally in CSV file.",
				iExpInputErr:	"Deine Angabe ist enweder keine Zahl oder nicht zwischen 11 und ",
				bImpBases: 		"Import Basen",
				tImpBases:		"Import Basen aus CSV Datei.",
				bImpShips:		"Import Schiffe",
				tImpShips:		"Import Schiffe aus CSV Datei.",
				bImpBookmarks:	"Import Lesezeichen",
				tImpBookmarks:	"Import Lesezeichen aus CSV Datei.",
				bExpComOneMap:	"Export Kommentar einer Map",
				tExpComOneMap: 	"Export Kommentar von einer Map in CSV Datei.",
				bExpComAllMaps:	"Export Kommentare aller Maps",
				tExpComAllMaps:	"Export Kommentare aller Maps in CSV Datei.",
				bImpComments:	"Import Kommentare",
				tImpComments:	"Import Kommentare aus CSV Datei.",
							
				// popups import	
				pBaseTitle:     "Basen aus CSV-Datei in die Datenbank importieren.",
				pShipTitle:		"Schiffe aus CSV-Datei in die Datenbank importieren.",
				pBookmarkTitle:	"Lesezeichen aus einer CSV-Datei in die Datenbank importieren.",
				pCommentTitle:	"Kartenkommentare aus einer CSV-Datei in die Datenbank importieren.",
				pDescription:   "Je nach Dateigröße kann der Import einige Minuten dauern.",
				pBtnChooseFile: "Datei auswählen...",
				pNoFileChosen:  "Keine Datei ausgewählt",
				pBtnImport:     "Daten importieren",
				pErrNoFile:     "Bitte eine CSV-Datei auswählen.",

				// popup map scanner
				sc_title:       "Karten-Scanner",
                sc_description: "Die angegebenen Karten werden der Reihe nach besucht und damit gespeichert.",
                sc_speed:       "Der Karten-Scanner verarbeitet ca.\u00a015\u201320 Karten pro Minute.",
                sc_attention:   "ACHTUNG:\u00a0Nicht zu oft verwenden!",
                sc_warning:     "Hoppe könnte solche regelmäßigen schnellen Anfragen bemerken.",
                sc_from:        "Von Kartennummer:",
                sc_to:          "Bis Kartennummer:",
                sc_rbBase:      "Nur Karten mit Basen oder Schiffen von mir.\u00a0",
                sc_rbShip1:     "Karten mit Basen und Schiffen meiner Ally\u00a0(ohne\u00a0meine Karten).",
                sc_rbShip:      "Karten mit Basen und Schiffen meiner Ally.",
                sc_rbShip2:     "Alle Karten ohne\u00a0Karten meiner Ally.",
                sc_rbAll:       "Alle Karten.",
                sc_btnStart:    "Scannen",
                sc_ttStart:     "Startet den Scan der angegebenen Karten.",
                sc_errMaxMap:   "Der Bis-Wert muss kleiner als die maximale Kartenanzahl sein! ({max})",
                sc_errFromTo:   "Der Von-Wert muss kleiner als der \"Bis\"-Wert sein!",
                sc_errMinFrom:  "Der Von-Wert muss 11 oder größer sein!",
			},
			fr: {
				impCompl: 		"L'importation est terminée.",
				added: 			"Ajouté : ",
				updated: 		"Mis à jour : ",
				skipped: 		"Ignoré : ",
				bluebtn: 		"Zoom sur la carte",
                ttCancel:      	"Annuler",
				ttStart:       	"Démarrer",
				tPoint:			".",
				
				// red button
				close1: 		"Fermer AstroSpy",
				redbtn: 		"Menu proposant d'autres fonctions",
				bAllUnits:		"Toutes les unités",
				tAllUnits:		"Ouvre une fenêtre contenant des informations sur toutes\nles cartes, tous les navires et toutes les bases\nprovenant des cartes déjà explorées.",
				bShipsPerMap:	"Mes navires par carte",
				tShipsPerMap:	"Ouvre une fenêtre présentant un aperçu des navires par carte.",
				bScanner:		"Scanner de cartes",
				tScanner:		"Ouvre une fenêtre contextuelle pour consulter/parcourir les cartes les unes après les autres.",
				bMessages:		"Afficher les messages",
				tMessages:		"Les dernières informations s'affichent.\nPar exemple, les ennemis sur une carte.",
				bChangePlAlly: 	"Changer l'allié d'un joueur",
				tChangePlAlly: 	"Ouvre une fenêtre contextuelle permettant de changer\nl'allié du joueur après qu'il en a sélectionné un autre.",
				bChangePlName: 	"Changer le nom d'un joueur",
				tChangePlName: 	"Ouvre une fenêtre contextuelle permettant de\nmodifier le nom d'un joueur lorsqu'il s'est renommé..",
				bResetMyAlly: 	"Réinitialiser mon Ally sur une carte",
				tResetMyAlly: 	"Utilise ce bouton pour réinitialiser la carte de ton alliée.",
				tpResetMyAlly1: "Cette fonction réinitialise les données de base de ton allié sur une seule carte.\nUtile si ton allié a perdu des bases.\nLe numéro de la carte doit être compris entre 11 et ",
				tpResetMyAlly2: "\nIMPORTANT : passe d'abord à une autre carte, sinon cela ne fonctionnera pas.",
				tpResetMyAlly3: "Tu essaies de réinitialiser les données de la carte actuellement active.\nPasse à une autre carte et réessaie.",
				bResetAnyAlly: 	"Réinitialiser n'importe quelle alliée sur une carte",
				tResetAnyAlly: 	"Utilise ce bouton pour réinitialiser\nn'importe quel allié sur la carte.",
				
				// green button
				bExpBasesOneMap:"Exporter les bases d'une carte",
				tExpBasesOneMap:"Exporter les bases d'une carte donnée vers un fichier CSV.",
				pExpBasOneMap1:	"Cette fonction exportera une carte vers un fichier CSV.\nLe fichier sera enregistré dans votre dossier TÉLÉCHARGEMENTS par défaut.\nLe numéro de la carte doit être supérieur à 10 et inférieur à ",
				pExpBasOneMap2:	".",
				bExpBasesAllMaps:"Exporter les bases de toutes les cartes",
				tExpBasesAllMaps:"Exporter les bases de données de toutes\nles cartes vers un fichier CSV.",
				pExpBasesAllMaps:"Cette fonction exporte toutes les cartes vers un fichier CSV.\nLe fichier sera enregistré dans votre dossier „TÉLÉCHARGEMENTS“ par défaut. Continuer ?",
				bExpBasesOnePl:	"Exporter les bases d'un joueur",
				tExpBasesOnePl:	"Exporter les bases d'un joueur vers un fichier CSV.",
				bExpBasesOneAl: "Exporter toutes les bases d'une alliée",
				tExpBasesOneAl:	"Exporter toutes les bases d'une alliée dans un fichier CSV.",
				iExpInputErr:	"La valeur que tu as saisie n'est pas un nombre ou n'est pas comprise entre 11 et ",
				bImpBases: 		"Importation des bases",
				tImpBases:		"Importer des bases de données à partir d'un fichier CSV.",
				bImpShips:		"Importation de navires",
				tImpShips:		"Importer des navires à partir d'un fichier CSV.",
				bImpBookmarks:	"Importer les signets",
				tImpBookmarks:	"Importer des signets à partir d'un fichier CSV.",
				bExpComOneMap:	"Exporter les commentaires d'une carte",
				tExpComOneMap: 	"Exporter les commentaires d'une carte spécifique vers un fichier CSV.",
				bExpComAllMaps:	"Exporter les commentaires de toutes les cartes",
				tExpComAllMaps:	"Exporter les commentaires de toutes les cartes dans un fichier CSV.",
				bImpComments:	"Importer les commentaires",
				tImpComments:	"Importer les commentaires depuis un fichier CSV.",

				
				// popups import
				pBaseTitle:     "Importer des bases de données depuis un fichier CSV vers votre base de données",
				pShipTitle:		"Importez des navires depuis un fichier CSV dans votre base de données.",
				pBookmarkTitle:	"Importez vos signets depuis un fichier CSV vers votre base de données.",
				pCommentTitle:	"Importer les commentaires de cartes d'un fichier CSV dans la base de données.",
				pDescription:   "Selon la taille du fichier, l'importation peut prendre quelques minutes.",
				pBtnChooseFile: "Sélectionner un fichier...",
				pNoFileChosen:  "Aucun fichier sélectionné",
				pBtnImport:     "Importer des données",
				pErrNoFile:     "Veuillez sélectionner un fichier CSV.",
				
				// popup map scanner
				sc_title:       "Scanner de cartes",
                sc_description: "Les cartes spécifiées sont visitées en séquence et ainsi sauvegardées.",
                sc_speed:       "Le scanner de cartes traite environ\u00a015\u201320 cartes par minute.",
                sc_attention:   "ATTENTION\u00a0: Évitez de l'utiliser trop souvent\u00a0!",
                sc_warning:     "Hoppe pourrait remarquer ces requêtes rapides et régulières.",
                sc_from:        "De la carte numéro\u00a0:",
                sc_to:          "Jusqu'à la carte numéro\u00a0:",
                sc_rbBase:      "Uniquement les cartes avec des bases ou des vaisseaux de moi.\u00a0",
                sc_rbShip1:     "Cartes avec bases et vaisseaux de mon allié\u00a0(sauf\u00a0mes cartes).",
                sc_rbShip:      "Cartes avec bases et vaisseaux de mon allié.",
                sc_rbShip2:     "Toutes les cartes sauf\u00a0celles de mon allié.",
                sc_rbAll:       "Toutes les cartes.",
                sc_btnStart:    "Scanner",
                sc_ttStart:     "Lance le scan des cartes spécifiées.",
                sc_errMaxMap:   "La valeur \"jusqu'à\" doit être inférieure au nombre maximum de cartes\u00a0! ({max})",
                sc_errFromTo:   "La valeur \"de\" doit être inférieure à la valeur \"jusqu'à\"\u00a0!",
                sc_errMinFrom:  "La valeur \"de\" doit être 11 ou plus\u00a0!",
			}
		};