export const lng_main = {
			en: {
				impCompl: 		"Import complete.",
				added: 			"Added: ",
				updated: 		"Updated: ",
				skipped: 		"Skipped: ",
				bluebtn: 		"Zoom window",
				ttCancel:      	"Cancel",
				ttStart:       	"Start",

				// red button
				close1: 		"Close AstroSpy",
				redbtn: 		"Menue with further features",
				bAllUnits:		"All units",
				tAllUnits:		"Opens a window with data on all maps, ships and bases\nfrom maps already visited.",
				bShipsPerMap:	"My ships per map",
				tShipsPerMap:	"Opens a window with overview of ships\nper map.",
				bScanner:		"Map Scanner",
				tScanner:		"Opens a pop-up window to automatically scan/visit\nmaps one after the other.",
				bMessages:		"Show messages",
				tMessages:		"Last messages will be shown, e.g. enemies on a map.",
				bChangePlAlly: 	"Change players's ally",
				tChangePlAlly: 	"Opens a pop-up window to change player's\nally after he flipped to a different one.",
				bChangePlName: 	"Change player's name",
				tChangePlName: 	"Opens a pop-up window to change player's\nname after he renamed.",
				bResetMyAlly:	"Reset my ally on a map",
				tResetMyAlly:	"Use this button to clear your ally base data on a map.",
				tpResetMyAlly1: "This function will reset the base data of your ally only on a map.\nUseful if your ally lost bases.\nMap number must be between 11 and ",
				tpResetMyAlly2: "\nIMPORTANT: switch first to a different map or it won't work.",
				tpResetMyAlly3: "You are trying to reset the data from the currently active map.\nSwitch to a different map and try again.",
				bResetAnyAlly: 	"Reset any ally on a map",
				tResetAnyAlly: 	"Use this button to clear your any base data on a map.",
				
				// green button
				bExpBasesOneMap:"Export bases of one map",
				tExpBasesOneMap:"Export bases of a particular map to a CSV file.",
				pExpBasOneMap1:	"This function will export a map to a CSV file.\nFile will be stored in your standard DOWNLOADS folder.\nMap number must be greater than 10 and less than",
				pExpBasOneMap2:	".",
				bExpBasesAllMaps:"Export bases of all maps",
				tExpBasesAllMaps:"Export bases of all maps to a CSV file.",
				pExpBasesAllMaps:"This function will export all maps to a CSV file.\nFile will be stored in your standard DOWNLOADS folder. Proceed?",
				iExpInputErr:	"Your input is either not numeric or not between 11 and ",
				bImpBases: 		"Import bases",
				tImpBases:		"Import bases from a CSV file.",
				bImpShips:		"Import ships",
				tImpShips:		"Import ships from a CSV file.",
				bImpBookmarks:	"Import bookmarks",
				tImpBookmarks:	"Import bookmarks from a CSV file.",
				bImpComments:	"Import comments",
				tImpComments:	"Import map comments from a CSV file.",				

				
				// popups import
				pBaseTitle:     "Import bases from CSV file to your database.",
				pShipTitle:		"Import ships from CSV file to your database.",
				pBookmarkTitle:	"Import bookmarks from CSV file to your database.",
				pCommentTitle:	"Import map comments from CSV file to your database.",
				pDescription:   "Depending on file size import might take up to a few minutes.",
				pBtnChooseFile: "Choose file...",
				pNoFileChosen:  "No file chosen",
				pBtnImport:     "Import Data",
				pErrNoFile:     "Please select a CSV file.",
			},
			de: {
				impCompl: 		"Import fertig.",
				added: 			"Hinzugefügt: ",
				updated: 		"Aktualisiert: ",
				skipped: 		"Übersprungen: ",
				bluebtn: 		"Zoom Fenster",
				ttCancel:      	"Abbrechen",
				ttStart:       	"Starten",

				// red button
				close1: 		"AstroSpy schließen",
				redbtn: 		"Menu mit weiteren Funktionen",
				bAllUnits:		"Alle Einheiten",
				tAllUnits:		"Öffnet ein Fenster mit Übersicht aller Karten, \nBasen und Schiffe der besuchten Karten.",
				bShipsPerMap:	"Meine Schiffe pro Karte",
				tShipsPerMap:	"Öffnet ein Fenster mit der Übersicht\nmeiner Schiffe pro Karte.",
				bScanner:		"Kartenscanner",
				tScanner:		"Öffnet ein Popup-Fenster, um die Karten\nnacheinender zu besuchen/scannen.",
				bMessages:		"Nachrichten anzeigen",
				tMessages:		"Letzte Nachrichten werden angezeigt.\nZ.B. Feinde auf einer Karte.",
				bChangePlAlly: 	"Ally eines Spieler's ändern",
				tChangePlAlly: 	"Öffnet ein Popup-Fenster, um die Ally des Spielers zu\nändern, nachdem er zu einer anderen gewechselt ist.",
				bChangePlName: 	"Name eines Spieler's ändern",
				tChangePlName: 	"Öffnet ein Popup Fenster, um den Namen eines\nSpieler's zu ändern wenn er sich umbenannt hat.",
				bResetMyAlly: 	"Reset meine Ally auf einer Karte",
				tResetMyAlly: 	"Verwende diesen Button, um die Map deiner Ally zurückzusetzen.",	
				tpResetMyAlly1: "Diese Funktion setzt die Basisdaten deiner Ally nur auf einer Karte zurück.\nNützlich, wenn deine Ally Basen verloren hat.\nDie Kartennummer muss zwischen 11 und ",
				tpResetMyAlly2: " sein.\nWICHTIG: Wechsle zuerst zu einer anderen Karte, sonst funktioniert es nicht.",
				tpResetMyAlly3: "Du versuchst, die Daten der derzeit aktiven Karte zurückzusetzen.\nWechsle zu einer anderen Karte und versuche es erneut.",
				bResetAnyAlly: 	"Reset irgendeine Ally auf einer Karte",
				tResetAnyAlly: 	"Verwende diesen Button, um irgendeine\nAlly auf der Map zurückzusetzen.",	
				
				// green button
				bExpBasesOneMap:"Export Basen von einer Karte",
				tExpBasesOneMap:"Export Basen von einer bestimmten Karte\nin eine CSV Datei.",
				pExpBasOneMap1:	"Diese Funktion exportiert eine Karte in eine CSV-Datei.\nDie Datei wird im Standardordner „DOWNLOADS“ gespeichert.\nDie Kartennummer muss größer als 10 und kleiner als ",
				pExpBasOneMap2:	" sein.",
				bExpBasesAllMaps:"Export Basen von allen Karten",
				tExpBasesAllMaps:"Export Basen aller Maps in CSV Datei.",
				pExpBasesAllMaps:"Diese Funktion exportiert alle Karten in eine CSV-Datei.\nDie Datei wird in Ihrem Standardordner „DOWNLOADS“ gespeichert. Fortfahren?",
				iExpInputErr:	"Deine Angabe ist enweder keine Zahl oder nicht zwischen 11 und ",
				bImpBases: 		"Import Basen",
				tImpBases:		"Import Basen aus CSV Datei.",
				bImpShips:		"Import Schiffe",
				tImpShips:		"Import Schiffe aus CSV Datei.",
				bImpBookmarks:	"Import Lesezeichen",
				tImpBookmarks:	"Import Lesezeichen aus CSV Datei.",
				bImpComments:	"Import Kommentare",
				tImpComments:	"Import Kommentare aus CSV Datei.",
				
				// popups import	
				pBaseTitle:     "Basen aus CSV-Datei in die Datenbank importieren.",
				pShipTitle:		"Schiffe aus CSV-Datei in die Datenbank importieren.",
				pBookmarkTitle:	"Lesezeichen aus einer CSV-Datei in die Datenbank importieren.",
				pCommentTitle:	"Kartenkommentare aus einer CSV-Datei in die Datenbank importieren.",
				pDescription:   "Je nach Dateigröße kann der Import einige Minuten dauern.",
				pBtnChooseFile: "Datei auswählen...",
				pNoFileChosen:  "Keine Datei ausgewählt",
				pBtnImport:     "Daten importieren",
				pErrNoFile:     "Bitte eine CSV-Datei auswählen."				
			},
			fr: {
				impCompl: 		"L'importation est terminée.",
				added: 			"Ajouté : ",
				updated: 		"Mis à jour : ",
				skipped: 		"Ignoré : ",
				bluebtn: 		"Zoom sur la carte",
                ttCancel:      	"Annuler",
				ttStart:       	"Démarrer",
				
				// red button
				close1: 		"Fermer AstroSpy",
				redbtn: 		"Menu proposant d'autres fonctions",
				bAllUnits:		"Toutes les unités",
				tAllUnits:		"Ouvre une fenêtre contenant des informations sur toutes\nles cartes, tous les navires et toutes les bases\nprovenant des cartes déjà explorées.",
				bShipsPerMap:	"Mes navires par carte",
				tShipsPerMap:	"Ouvre une fenêtre présentant un aperçu des navires par carte.",
				bScanner:		"Scanner de cartes",
				tScanner:		"Ouvre une fenêtre contextuelle pour consulter/parcourir les cartes les unes après les autres.",
				bMessages:		"Afficher les messages",
				tMessages:		"Les dernières informations s'affichent.\nPar exemple, les ennemis sur une carte.",
				bChangePlAlly: 	"Changer l'allié d'un joueur",
				tChangePlAlly: 	"Ouvre une fenêtre contextuelle permettant de changer\nl'allié du joueur après qu'il en a sélectionné un autre.",
				bChangePlName: 	"Changer le nom d'un joueur",
				tChangePlName: 	"Ouvre une fenêtre contextuelle permettant de\nmodifier le nom d'un joueur lorsqu'il s'est renommé..",
				bResetMyAlly: 	"Réinitialiser mon Ally sur une carte",
				tResetMyAlly: 	"Utilise ce bouton pour réinitialiser la carte de ton alliée.",
				tpResetMyAlly1: "Cette fonction réinitialise les données de base de ton allié sur une seule carte.\nUtile si ton allié a perdu des bases.\nLe numéro de la carte doit être compris entre 11 et ",
				tpResetMyAlly2: "\nIMPORTANT : passe d'abord à une autre carte, sinon cela ne fonctionnera pas.",
				tpResetMyAlly3: "Tu essaies de réinitialiser les données de la carte actuellement active.\nPasse à une autre carte et réessaie.",
				bResetAnyAlly: 	"Réinitialiser n'importe quelle alliée sur une carte",
				tResetAnyAlly: 	"Utilise ce bouton pour réinitialiser\nn'importe quel allié sur la carte.",
				
				// green button
				bExpBasesOneMap:"Exporter les bases d'une carte",
				tExpBasesOneMap:"Exporter les bases d'une carte donnée vers un fichier CSV.",
				pExpBasOneMap1:	"Cette fonction exportera une carte vers un fichier CSV.\nLe fichier sera enregistré dans votre dossier TÉLÉCHARGEMENTS par défaut.\nLe numéro de la carte doit être supérieur à 10 et inférieur à ",
				pExpBasOneMap2:	".",
				bExpBasesAllMaps:"Exporter les bases de toutes les cartes",
				tExpBasesAllMaps:"Exporter les bases de données de toutes\nles cartes vers un fichier CSV.",
				pExpBasesAllMaps:"Cette fonction exporte toutes les cartes vers un fichier CSV.\nLe fichier sera enregistré dans votre dossier „TÉLÉCHARGEMENTS“ par défaut. Continuer ?",
				iExpInputErr:	"La valeur que tu as saisie n'est pas un nombre ou n'est pas comprise entre 11 et ",
				bImpBases: 		"Importation des bases",
				tImpBases:		"Importer des bases de données à partir d'un fichier CSV.",
				bImpShips:		"Importation de navires",
				tImpShips:		"Importer des navires à partir d'un fichier CSV.",
				bImpBookmarks:	"Importer les signets",
				tImpBookmarks:	"Importer des signets à partir d'un fichier CSV.",
				bImpComments:	"Importer les commentaires",
				tImpComments:	"Importer les commentaires depuis un fichier CSV.",				
				
				// popups import
				pBaseTitle:     "Importer des bases de données depuis un fichier CSV vers votre base de données",
				pShipTitle:		"Importez des navires depuis un fichier CSV dans votre base de données.",
				pBookmarkTitle:	"Importez vos signets depuis un fichier CSV vers votre base de données.",
				pCommentTitle:	"Importer les commentaires de cartes d'un fichier CSV dans la base de données.",
				pDescription:   "Selon la taille du fichier, l'importation peut prendre quelques minutes.",
				pBtnChooseFile: "Sélectionner un fichier...",
				pNoFileChosen:  "Aucun fichier sélectionné",
				pBtnImport:     "Importer des données",
				pErrNoFile:     "Veuillez sélectionner un fichier CSV."
			}
		};